default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  host: <%= ENV.fetch("MYSQL_HOST", "db") %>

development:
  <<: *default
  database: sql_master_development

test:
  <<: *default
  database: sql_master_test

production:
  <<: *default
  database: sql_master_production
  username: sql_master
  password: <%= ENV['SQL_MASTER_DATABASE_PASSWORD'] %>
